# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('name', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=25)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('I', 'Incomplete'), ('P', 'In Progress'), ('C', 'Complete')], max_length=1)),
                ('realShippingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predictedShippingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userOrdered', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='referenceOrder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Order'),
        ),
    ]
