# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dimensions',
            field=models.CharField(max_length=40),
        ),
    ]
