# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-24 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_auto_20180223_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='637659'),
            preserve_default=False,
        ),
    ]
