# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-24 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0003_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='userOrdered',
        ),
        migrations.AddField(
            model_name='order',
            name='userOrdered',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
