# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-24 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20180224_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='referenceOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='v1.Item'),
        ),
    ]
